import { subDays, formatISO } from "date-fns";
import type { DashboardTrade } from "@/components/dashboard/types";

export const demoTrades: DashboardTrade[] = [
  {
    id: "demo-1",
    pair: "XAUUSD",
    direction: "long",
    entry_price: 2318.4,
    exit_price: 2326.8,
    pnl: 184,
    risk_reward: 2.4,
    outcome: "win",
    opened_at: formatISO(subDays(new Date(), 1)),
    closed_at: formatISO(subDays(new Date(), 1)),
  },
  {
    id: "demo-2",
    pair: "EURUSD",
    direction: "short",
    entry_price: 1.0834,
    exit_price: 1.0802,
    pnl: 96,
    risk_reward: 2.1,
    outcome: "win",
    opened_at: formatISO(subDays(new Date(), 2)),
    closed_at: formatISO(subDays(new Date(), 2)),
  },
  {
    id: "demo-3",
    pair: "BTCUSD",
    direction: "long",
    entry_price: 67210,
    exit_price: 66880,
    pnl: -72,
    risk_reward: 1.8,
    outcome: "loss",
    opened_at: formatISO(subDays(new Date(), 3)),
    closed_at: formatISO(subDays(new Date(), 3)),
  },
  {
    id: "demo-4",
    pair: "GBPJPY",
    direction: "short",
    entry_price: 199.82,
    exit_price: 199.21,
    pnl: 128,
    risk_reward: 2.7,
    outcome: "win",
    opened_at: formatISO(subDays(new Date(), 5)),
    closed_at: formatISO(subDays(new Date(), 5)),
  },
  {
    id: "demo-5",
    pair: "USDJPY",
    direction: "long",
    entry_price: 156.24,
    exit_price: 156.18,
    pnl: -38,
    risk_reward: 1.3,
    outcome: "loss",
    opened_at: formatISO(subDays(new Date(), 7)),
    closed_at: formatISO(subDays(new Date(), 7)),
  },
];
